[package]
name = "vulpine"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.0.1", features = ["rustls"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
envy = "0.4.2"
log = "0.4.14"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
