on:
  push:
    tags:
     - v*.*.*

jobs:
  docker:
    uses: ilmannafian04/.github/workflows/docker.yml@main
    with:
      username: ilmannafian
      repository: ilmannafian
      app-name: vulpine
