name: docker
on:
  push:
    tags:
     - v*.*.*

jobs:
  docker:
    uses: ilmannafian04/dot-github/.github/workflows/docker.yml@main
    with:
      username: ilmannafian
      repository: ilmannafian
      app-name: vulpine
    secrets:
      docker-hub-access-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
